# Generated by Django 5.1.3 on 2024-12-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0002_category_group_expense_expensesplit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
