# Generated by Django 5.1.3 on 2024-12-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0003_account_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.AddField(
            model_name='account',
            name='is_credit_care',
            field=models.BooleanField(default=False),
        ),
    ]
