# Generated by Django 5.1.3 on 2024-12-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0004_remove_account_account_type_account_is_credit_care'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_credit_care',
            new_name='is_credit_card',
        ),
    ]
