# Generated by Django 5.1.3 on 2024-12-08 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintrack', '0008_alter_expense_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_investment',
        ),
        migrations.AddField(
            model_name='expense',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='expense_transactions', to='fintrack.transaction'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expenses',
            field=models.ManyToManyField(blank=True, related_name='transaction_expenses', to='fintrack.expense'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fintrack.category'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category'], name='fintrack_ex_user_id_627410_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'group', 'date'], name='fintrack_tr_user_id_997d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='fintrack_tr_date_8d7a2a_idx'),
        ),
    ]
