# Generated by Django 5.1.3 on 2024-12-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fintrack', '0013_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lend', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_transactions', to='fintrack.counterparty')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_transactions', to='fintrack.transaction')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['transaction', 'counterparty', 'date'], name='fintrack_mo_transac_8a6745_idx'), models.Index(fields=['date'], name='fintrack_mo_date_74e0fd_idx')],
            },
        ),
    ]
