# Generated by Django 5.1.3 on 2024-12-11 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('finassist', '0001_initial'), ('finassist', '0002_processed_data'), ('finassist', '0003_email'), ('finassist', '0004_email_is_processed_email_label_email_plain_text_body_and_more'), ('finassist', '0005_email_snippet'), ('finassist', '0006_email_from_email_name_email_raw_html_and_more'), ('finassist', '0007_rename_email_body_email_raw_text_and_more'), ('finassist', '0008_taskstatus'), ('finassist', '0009_remove_taskstatus_finassist_t_task_ty_b14e9a_idx_and_more'), ('finassist', '0010_alter_taskstatus_object_id'), ('finassist', '0011_taskstatus_data'), ('finassist', '0012_taskstatus_is_archived')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, unique=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('txt', 'Text')], max_length=50)),
                ('regex_pattern', models.TextField(blank=True, null=True)),
                ('column_mapping', models.JSONField(blank=True, null=True)),
                ('date_format', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='processed_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
                ('is_processed', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('processed_text', models.TextField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('from_email_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('STATEMENT_PARSING', 'Statement Parsing'), ('MAIL_PARSING', 'Mail Parsing'), ('SMS_PARSING', 'SMS Parsing')], max_length=50)),
                ('task_stage', models.CharField(choices=[('PARSER', 'Parser'), ('AI', 'AI Parsing')], default='PARSER', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('object_id', models.UUIDField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [],
            },
        ),
    ]
