# Generated by Django 5.1.3 on 2024-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finassist', '0003_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='plain_text_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='processed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
