# Generated by Django 5.1.3 on 2024-12-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finassist', '0004_email_is_processed_email_label_email_plain_text_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
