# Generated by Django 5.1.3 on 2024-12-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finassist', '0005_email_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='from_email_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
